
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvLZB_RhiLaEnQpKNhliQhKViXH-JngHE',
    appId: '1:887114857127:web:9cd3cbb255881016253982',
    messagingSenderId: '887114857127',
    projectId: 'news-app-5e026',
    authDomain: 'news-app-5e026.firebaseapp.com',
    storageBucket: 'news-app-5e026.appspot.com',
    measurementId: 'G-DNKBZW8L31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYa68UvFLXtHM_YrWba0mxN9Ee7taE0L8',
    appId: '1:887114857127:android:39b39fbb84e914fd253982',
    messagingSenderId: '887114857127',
    projectId: 'news-app-5e026',
    storageBucket: 'news-app-5e026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARn6hLUsntwP9Z1n8h6ldnYuQ-u5ZRfI4',
    appId: '1:887114857127:ios:19ea09360cd20dd1253982',
    messagingSenderId: '887114857127',
    projectId: 'news-app-5e026',
    storageBucket: 'news-app-5e026.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARn6hLUsntwP9Z1n8h6ldnYuQ-u5ZRfI4',
    appId: '1:887114857127:ios:19ea09360cd20dd1253982',
    messagingSenderId: '887114857127',
    projectId: 'news-app-5e026',
    storageBucket: 'news-app-5e026.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvLZB_RhiLaEnQpKNhliQhKViXH-JngHE',
    appId: '1:887114857127:web:679e8902eccb88a7253982',
    messagingSenderId: '887114857127',
    projectId: 'news-app-5e026',
    authDomain: 'news-app-5e026.firebaseapp.com',
    storageBucket: 'news-app-5e026.appspot.com',
    measurementId: 'G-06XK3WKNLH',
  );
}
